import react from 'react'
import { createContext } from 'react'

export const ContextApiItem = createContext({
    // APIdata:{},
    HeadUserDash : "/Login",
    setHeadUserDash : () => {},
    setId : () => {},
    id : "",
    methodPro: () => {},
    setMethod:{},
    textSuccess:{},
    setTextSuccess: () => {},
    Postmethod:{},
    setPostMethod: () => {},
    IdPost:{},
    setIdPost: () => {},
    PostMsgSuccess:{},
    setPostMsgSuccess: () => {},
    ProductIdIntrested:{},
    setProductIdIntrested: () => {},
    ProductCpmparison : {},
    setProductCpmparison : () => {},
    BasketProduct : {},
    setBasketProduct:() => {},
    Tickets:{},
    setTickets: () => {},
    SinglePostData:{},
    setSinglePostData: () => {},
    BasketCount : {},
    setBasketCount: () => {},
    ContentPageProduct : {},
    setContentPageProduct : () => {},
    UserTicketId : {},
    setUserTicketId : () => {},
    ProId : {},
    setProId : () => {},
    SellPro : {},
    setSellPro : () => {},
    ImgData:{},
    setImgData:() => {},
})


